name: Déploiement continu

on:
  push:
    branches: ["development"] # Déclencher le workflow lorsqu'un commit est effectué sur la branche development
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Construction de l'image Docker
        run: |
          docker build -t ressourses-formation:latest .

      # Arrêt et suppression du conteneur s'il existe
      - name: Stop and Remove existing Docker container
        run: |
          docker stop ressourses-formation || true
          docker rm ressourses-formation || true

      # Création et démarrage d'un nouveau conteneur Docker
      - name: Run Docker container
        run: |
          docker run -d --name ressourses-formation ressourses-formation:latest

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4